import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Calender from './Calender'

export default function Home() {
  return (
    <div className='bg-gray-100 '>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Calender/>
    </div>
  )
}
